apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcareapp-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcareapp-container
        image: madhavan2454/project-healthcareapp-img:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcareapp-nodeport-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app

  type: NodePort
  ports:
  - nodePort: 31032  
    port: 8082
    targetPort: 8082
